# -*- coding: utf-8 -*-
"""CP-2_NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MTCgcMXHgIDOUieei-f88P9LDyV-WMI
"""

!python -m spacy download pt_core_news_sm
!pip install sumy

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

from nltk.tokenize import word_tokenize, sent_tokenize

# Texto fornecido
texto = "Aurora's Realm: The Enchanted Adventure narra a história de Liam, Elena e sua filha Aurora em um mundo mágico onde elfos, fadas e humanos vivem em harmonia. Quando um feiticeiro das trevas chamado Malachai ameaça o equilíbrio, Liam e Elena se unem a um grupo de heróis para derrotá-lo. Após vencer Malachai, uma reviravolta sombria acontece quando um seguidor do feiticeiro sequestra Aurora, desencadeando uma nova jornada de perigos e desafios. Com a ajuda de aliados, Liam e Elena enfrentam tribos poderosas e reúnem forças para resgatar sua filha e restaurar a paz. Na nova era do jogo, os jogadores exploram o mundo mágico, participam de batalhas, formam laços familiares e de amizade, além de poderem se envolver em atividades como pesca e cultivo de jardins. Com cada desafio enfrentado, os jogadores desenvolvem suas habilidades e se tornam parte de uma aventura emocionante e encantadora em Aurora's Realm - O Mundo dos Sonhos."

# Tokenização de palavras
tokens_palavras = word_tokenize(texto)

# Tokenização de sentenças
tokens_sentencas = sent_tokenize(texto)

print("Tokens de palavras:", tokens_palavras)
print("Tokens de sentenças:", tokens_sentencas)

import spacy

# Carregando modelo pré-treinado em português
nlp = spacy.load("pt_core_news_sm")

# Texto fornecido
texto = "Aurora's Realm: The Enchanted Adventure narra a história de Liam, Elena e sua filha Aurora em um mundo mágico onde elfos, fadas e humanos vivem em harmonia. Quando um feiticeiro das trevas chamado Malachai ameaça o equilíbrio, Liam e Elena se unem a um grupo de heróis para derrotá-lo. Após vencer Malachai, uma reviravolta sombria acontece quando um seguidor do feiticeiro sequestra Aurora, desencadeando uma nova jornada de perigos e desafios. Com a ajuda de aliados, Liam e Elena enfrentam tribos poderosas e reúnem forças para resgatar sua filha e restaurar a paz. Na nova era do jogo, os jogadores exploram o mundo mágico, participam de batalhas, formam laços familiares e de amizade, além de poderem se envolver em atividades como pesca e cultivo de jardins. Com cada desafio enfrentado, os jogadores desenvolvem suas habilidades e se tornam parte de uma aventura emocionante e encantadora em Aurora's Realm - O Mundo dos Sonhos."

# Processamento do texto
doc = nlp(texto)

# Identificação de entidades nomeadas
entidades_nomeadas = [(ent.text, ent.label_) for ent in doc.ents]

print("Entidades nomeadas identificadas:", entidades_nomeadas)

from nltk import pos_tag

# Tokenização de palavras
tokens_palavras = word_tokenize(texto)

# Análise de etiquetas gramaticais
etiquetas_gramaticais = pos_tag(tokens_palavras)

print("Etiquetas gramaticais das palavras:", etiquetas_gramaticais)

from gensim.models import LdaModel
from gensim.corpora import Dictionary

# Documentos de exemplo
documentos = ["Este é um documento sobre análise de dados.",
              "Análise de dados envolve processamento e interpretação de informações.",
              "Processamento de linguagem natural é uma técnica importante para análise de dados."]

# Tokenização de palavras
tokens_documentos = [word_tokenize(doc) for doc in documentos]

# Criação do dicionário de palavras
dicionario = Dictionary(tokens_documentos)

# Conversão para Bag of Words
corpus = [dicionario.doc2bow(tokens) for tokens in tokens_documentos]

# Modelo LDA
modelo_lda = LdaModel(corpus, num_topics=2, id2word=dicionario)

# Visualização dos tópicos
for idx, topico in modelo_lda.print_topics(-1):
    print(f"Tópico {idx}: {topico}")

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer

def resumir_texto(texto, num_sentencas=2):
    # Crie um analisador de texto
    parser = PlaintextParser.from_string(texto, Tokenizer("portuguese"))

    # Crie um sumarizador LSA
    sumarizador = LsaSummarizer()

    # Gere o resumo
    resumo = sumarizador(parser.document, num_sentencas)

    # Converta o resumo em uma string
    resumo_texto = " ".join([str(sentença) for sentença in resumo])

    return resumo_texto

# Texto fornecido
texto = "Aurora's Realm: The Enchanted Adventure narra a história de Liam, Elena e sua filha Aurora em um mundo mágico onde elfos, fadas e humanos vivem em harmonia. Quando um feiticeiro das trevas chamado Malachai ameaça o equilíbrio, Liam e Elena se unem a um grupo de heróis para derrotá-lo. Após vencer Malachai, uma reviravolta sombria acontece quando um seguidor do feiticeiro sequestra Aurora, desencadeando uma nova jornada de perigos e desafios. Com a ajuda de aliados, Liam e Elena enfrentam tribos poderosas e reúnem forças para resgatar sua filha e restaurar a paz. Na nova era do jogo, os jogadores exploram o mundo mágico, participam de batalhas, formam laços familiares e de amizade, além de poderem se envolver em atividades como pesca e cultivo de jardins. Com cada desafio enfrentado, os jogadores desenvolvem suas habilidades e se tornam parte de uma aventura emocionante e encantadora em Aurora's Realm - O Mundo dos Sonhos."

# Resumir o texto
resumo = resumir_texto(texto)

print("Resumo automático:")
print(resumo)